### ISSUE TITLE
我在stackoverflow看到了你的提问

### ISSUE THREAD

**Issue by hpyperry** [tsingheng/exception-handler-demo#1]
应该是实现`ResponseBodyAdvice`的beforeWriteBody导致的错误，这个方法会在异常处理方法之前执行，修改Body
如果你不需要在请求前对请求的body进行一些数据处理等，不需要实现这个接口

**Comment by tsingheng** [comment]
是想通过`ResponseBodyAdvice`来实现接口响应结果使用统一模型，通过`@ErrorHandler`处理异常，如果是响应结果序列化异常，即使没有`ResponseBodyAdvice`，最终json也是两端，似乎是jackson序列化的时候已经把一部分json写到`Response`中了，`@ErrorHandler`处理异常返回结果后jackson又序列化一次，最终输出了两段json。
